[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#FF7F00"
backgroundColor = "#FFF9F3"
secondaryBackgroundColor = "#FFF1E2"
textColor = "#2D1B0E"
font = "sans-serif"
